// Generated by CoffeeScript 1.12.4
var FgCyan, FgGreen, FgRed, FgYellow, Reset, SpeechToTextURL, ToneAnalyzerURL, Watson, colors, fs, got;

colors = require('colors');

got = require('got');

fs = require('fs');

SpeechToTextURL = "https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?continuous=true";

ToneAnalyzerURL = "https://gateway.watsonplatform.net/tone-analyzer/api/v3/tone?version=2016-05-19";

Reset = "\x1b[0m";

FgRed = "\x1b[31m";

FgGreen = "\x1b[32m";

FgYellow = "\x1b[33m";

FgCyan = "\x1b[36m";

Watson = {
  creds: {
    username: "",
    password: ""
  },
  init: function(options) {
    Watson.creds.username = options.username;
    return Watson.creds.password = options.password;
  },
  speechToText: function(options) {
    var ProgressBar, auth, bar, data, fileSizeInBytes, fileStats, sizeInMB, stream, uploaded;
    auth = "Basic " + new Buffer(Watson.creds.username + ":" + Watson.creds.password).toString("base64");
    data = fs.readFileSync(options.audio_file);
    uploaded = 0;
    fileStats = fs.statSync(options.audio_file);
    fileSizeInBytes = fileStats.size;
    sizeInMB = (fileSizeInBytes / (1024 * 1024)).toFixed(2);
    if (sizeInMB > 100) {
      console.log("Error: file size exceeds maximum 100MB limit.".red);
      return Promise.resolve({
        msg: "Error: file size exceeds maximum 100MB limit.",
        error: true
      });
    }
    ProgressBar = require('progress');
    bar = new ProgressBar('Uploading [:bar] :percent :etas', {
      complete: FgRed + "▇" + Reset,
      incomplete: ' ',
      width: 20,
      total: fileSizeInBytes
    });
    stream = fs.createReadStream(options.audio_file);
    stream.on('data', function(chunk) {
      var uploadedPercentage;
      uploaded += chunk.length;
      uploadedPercentage = ((uploaded / fileSizeInBytes) * 100).toFixed();
      bar.tick(chunk.length);
      if (uploadedPercentage > 25) {
        bar.chars.complete = FgYellow + "▇" + Reset;
      }
      if (uploadedPercentage > 50) {
        bar.chars.complete = FgCyan + "▇" + Reset;
      }
      if (uploadedPercentage > 75) {
        return bar.chars.complete = FgGreen + "▇" + Reset;
      }
    });
    return got.post(SpeechToTextURL, {
      json: true,
      body: stream,
      encoding: null,
      headers: {
        "Authorization": auth,
        "Content-Type": "audio/wav",
        "Transfer-Encoding": "chunked"
      }
    }).then(function(res) {
      var output, results;
      results = res.body;
      output = {
        msg: "",
        statusCode: res.statusCode,
        data: JSON.stringify(results)
      };
      if (options.output) {
        output.msg = "Results written to file.";
        fs.writeFileSync(options.output, JSON.stringify(results), "utf8");
      }
      return output;
    })["catch"](function(error) {
      return console.log("Error", error);
    });
  },
  toneAnalyzer: function(options) {
    var auth;
    auth = "Basic " + new Buffer(Watson.creds.username + ":" + Watson.creds.password).toString("base64");
    return new Promise(function(resolve, reject) {
      return got.post(ToneAnalyzerURL, {
        json: true,
        body: JSON.stringify({
          text: options.text
        }),
        headers: {
          "Authorization": auth,
          "Content-Type": "application/json"
        }
      }).then(function(res) {
        var results;
        results = res.body;
        return resolve({
          msg: "",
          text: options.text,
          emotion_tone: results.document_tone.tone_categories[0].tones
        });
      })["catch"](console.log);
    });
  }
};

module.exports = Watson;


/* EXAMPLE RESPONSE "I am sad. My dog died."
{
  "document_tone": {
    "tone_categories": [
      {
        "tones": [
          {
            "score": 0.039917,
            "tone_id": "anger",
            "tone_name": "Anger"
          },
          {
            "score": 0.063371,
            "tone_id": "disgust",
            "tone_name": "Disgust"
          },
          {
            "score": 0.259677,
            "tone_id": "fear",
            "tone_name": "Fear"
          },
          {
            "score": 0.003858,
            "tone_id": "joy",
            "tone_name": "Joy"
          },
          {
            "score": 0.839898,
            "tone_id": "sadness",
            "tone_name": "Sadness"
          }
        ],
        "category_id": "emotion_tone",
        "category_name": "Emotion Tone"
      },
      {
        "tones": [
          {
            "score": 0,
            "tone_id": "analytical",
            "tone_name": "Analytical"
          },
          {
            "score": 0,
            "tone_id": "confident",
            "tone_name": "Confident"
          },
          {
            "score": 0,
            "tone_id": "tentative",
            "tone_name": "Tentative"
          }
        ],
        "category_id": "language_tone",
        "category_name": "Language Tone"
      },
      {
        "tones": [
          {
            "score": 0.011977,
            "tone_id": "openness_big5",
            "tone_name": "Openness"
          },
          {
            "score": 0.080594,
            "tone_id": "conscientiousness_big5",
            "tone_name": "Conscientiousness"
          },
          {
            "score": 0.221313,
            "tone_id": "extraversion_big5",
            "tone_name": "Extraversion"
          },
          {
            "score": 0.578512,
            "tone_id": "agreeableness_big5",
            "tone_name": "Agreeableness"
          },
          {
            "score": 0.000141,
            "tone_id": "emotional_range_big5",
            "tone_name": "Emotional Range"
          }
        ],
        "category_id": "social_tone",
        "category_name": "Social Tone"
      }
    ]
  },
  "sentences_tone": [
    {
      "sentence_id": 0,
      "text": "I am sad.",
      "input_from": 0,
      "input_to": 9,
      "tone_categories": [
        {
          "tones": [
            {
              "score": 0,
              "tone_id": "anger",
              "tone_name": "Anger"
            },
            {
              "score": 0,
              "tone_id": "disgust",
              "tone_name": "Disgust"
            },
            {
              "score": 0,
              "tone_id": "fear",
              "tone_name": "Fear"
            },
            {
              "score": 0,
              "tone_id": "joy",
              "tone_name": "Joy"
            },
            {
              "score": 1,
              "tone_id": "sadness",
              "tone_name": "Sadness"
            }
          ],
          "category_id": "emotion_tone",
          "category_name": "Emotion Tone"
        },
        {
          "tones": [
            {
              "score": 0,
              "tone_id": "analytical",
              "tone_name": "Analytical"
            },
            {
              "score": 0,
              "tone_id": "confident",
              "tone_name": "Confident"
            },
            {
              "score": 0,
              "tone_id": "tentative",
              "tone_name": "Tentative"
            }
          ],
          "category_id": "language_tone",
          "category_name": "Language Tone"
        },
        {
          "tones": [
            {
              "score": 0.099743,
              "tone_id": "openness_big5",
              "tone_name": "Openness"
            },
            {
              "score": 0.266958,
              "tone_id": "conscientiousness_big5",
              "tone_name": "Conscientiousness"
            },
            {
              "score": 0.491097,
              "tone_id": "extraversion_big5",
              "tone_name": "Extraversion"
            },
            {
              "score": 0.594667,
              "tone_id": "agreeableness_big5",
              "tone_name": "Agreeableness"
            },
            {
              "score": 0.038076,
              "tone_id": "emotional_range_big5",
              "tone_name": "Emotional Range"
            }
          ],
          "category_id": "social_tone",
          "category_name": "Social Tone"
        }
      ]
    },
    {
      "sentence_id": 1,
      "text": "My dog died.",
      "input_from": 10,
      "input_to": 22,
      "tone_categories": [
        {
          "tones": [
            {
              "score": 0.071539,
              "tone_id": "anger",
              "tone_name": "Anger"
            },
            {
              "score": 0.168703,
              "tone_id": "disgust",
              "tone_name": "Disgust"
            },
            {
              "score": 0.244503,
              "tone_id": "fear",
              "tone_name": "Fear"
            },
            {
              "score": 0.028376,
              "tone_id": "joy",
              "tone_name": "Joy"
            },
            {
              "score": 0.686877,
              "tone_id": "sadness",
              "tone_name": "Sadness"
            }
          ],
          "category_id": "emotion_tone",
          "category_name": "Emotion Tone"
        },
        {
          "tones": [
            {
              "score": 0,
              "tone_id": "analytical",
              "tone_name": "Analytical"
            },
            {
              "score": 0,
              "tone_id": "confident",
              "tone_name": "Confident"
            },
            {
              "score": 0,
              "tone_id": "tentative",
              "tone_name": "Tentative"
            }
          ],
          "category_id": "language_tone",
          "category_name": "Language Tone"
        },
        {
          "tones": [
            {
              "score": 0.208221,
              "tone_id": "openness_big5",
              "tone_name": "Openness"
            },
            {
              "score": 0.273372,
              "tone_id": "conscientiousness_big5",
              "tone_name": "Conscientiousness"
            },
            {
              "score": 0.536444,
              "tone_id": "extraversion_big5",
              "tone_name": "Extraversion"
            },
            {
              "score": 0.599567,
              "tone_id": "agreeableness_big5",
              "tone_name": "Agreeableness"
            },
            {
              "score": 0.224992,
              "tone_id": "emotional_range_big5",
              "tone_name": "Emotional Range"
            }
          ],
          "category_id": "social_tone",
          "category_name": "Social Tone"
        }
      ]
    }
  ]
}
 */
